#ifndef CYGONCE_PKGCONF_DEVS_SPI_CORTEXM_STM32_H
#define CYGONCE_PKGCONF_DEVS_SPI_CORTEXM_STM32_H
/*
 * File <pkgconf/devs_spi_cortexm_stm32.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_DEVS_SPI_CORTEXM_STM32_PIN_TOGGLE_RATE 2
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_PIN_TOGGLE_RATE_2
#define CYGHWR_DEVS_SPI_CORTEXM_STM32_BUS1 1
#define CYGHWR_DEVS_SPI_CORTEXM_STM32_BUS1_CS_GPIOS 4
#define CYGHWR_DEVS_SPI_CORTEXM_STM32_BUS1_CS_GPIOS_4
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_BBUF_SIZE 0
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_BBUF_SIZE_0
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_TXINTR_PRI 5
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_TXINTR_PRI_5
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_RXINTR_PRI 6
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_RXINTR_PRI_6

#endif
