#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_STM32_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_STM32_H
/*
 * File <pkgconf/hal_cortexm_stm32.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGHWR_HAL_CORTEXM_STM32 F103VC
#define CYGHWR_HAL_CORTEXM_STM32_F103VC
#define CYGNUM_HAL_CORTEXM_PRIORITY_LEVEL_BITS 4
#define CYGNUM_HAL_CORTEXM_PRIORITY_LEVEL_BITS_4
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK 1
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PLL_SOURCE HSE
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PLL_SOURCE_HSE
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PLL_MUL 4
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PLL_MUL_4
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_HCLK_DIV 1
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_HCLK_DIV_1
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PCLK1_DIV 8
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PCLK1_DIV_8
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PCLK2_DIV 1
#define CYGHWR_HAL_CORTEXM_STM32_CLOCK_PCLK2_DIV_1
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY 0x000000E0
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY_0x000000E0
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 500
#define CYGNUM_HAL_RTC_DENOMINATOR_500
#define CYGNUM_HAL_RTC_PERIOD 2000
#define CYGNUM_HAL_RTC_PERIOD_2000
#define CYGINT_HAL_STM32_UART0 1
#define CYGINT_HAL_STM32_UART0_1
#define CYGINT_HAL_STM32_UART1 1
#define CYGINT_HAL_STM32_UART1_1
#define CYGINT_HAL_STM32_UART2 0
#define CYGINT_HAL_STM32_UART2_0
#define CYGINT_HAL_STM32_UART3 0
#define CYGINT_HAL_STM32_UART3_0
#define CYGINT_HAL_STM32_UART4 0
#define CYGINT_HAL_STM32_UART4_0
#define CYGHWR_HAL_STM32_UART2_REMAP NONE
#define CYGHWR_HAL_STM32_UART2_REMAP_NONE
#define CYGPKG_HAL_CORTEXM_STM32_OPTIONS 1

#endif
